export const appEvent = 'app:status';
export const liveViewersEvent = 'live:viewers';
export const ipcNames = {
  getStatus: 'status:get',
  saveSettings: 'settings:save',
  openNsoLogin: 'nso:login',
  clearNsoLogin: 'nso:clear-login',
  unbindNso: 'nso:unbind',
  startQqLogin: 'qq:login',
  unbindQq: 'qq:unbind',
  listMatches: 'match:list',
  getThumb: 'match:thumb',
  openMatch: 'match:open',
  saveMatch: 'match:save',
  deleteMatch: 'match:delete',
  getVideoUrl: 'video:url',
  writeChunk: 'record:chunk',
  writeSegment: 'record:segment',
  reportCapture: 'record:report',
  debugExport: 'debug:export',
  openPath: 'path:open',
  pickFolder: 'folder:pick',
  openLink: 'link:open',
  finishSetup: 'setup:finish',
  startLive: 'live:start',
  stopLive: 'live:stop',
  liveChunk: 'live:chunk',
  startBlur: 'blur:start',
  writeBlurChunk: 'blur:chunk',
  endBlur: 'blur:end',
  cancelBlur: 'blur:cancel',
  startDetect: 'detect:start',
  detectFrame: 'detect:frame',
  stopDetect: 'detect:stop',
  copyText: 'clipboard:write',
  openPreview: 'preview:open',
  getRuntimeInfo: 'runtime:info',
} as const;
